<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12475" started-at="2016-02-02T17:27:20Z" finished-at="2016-02-02T17:27:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12475" started-at="2016-02-02T17:27:20Z" finished-at="2016-02-02T17:27:32Z">
      <class name="com.catalyst.springboot.security.LoginSeleniumTest">
        <test-method status="FAIL" signature="LoginFailure()[pri:0, instance:com.catalyst.springboot.security.LoginSeleniumTest@39fb3ab6]" name="LoginFailure" duration-ms="9051" started-at="2016-02-02T09:27:20Z" finished-at="2016-02-02T09:27:29Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...lhost:8080/loginPage[]> but was:<...lhost:8080/loginPage[#/home]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...lhost:8080/loginPage[]> but was:<...lhost:8080/loginPage[#/home]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at com.catalyst.springboot.security.LoginSeleniumTest.LoginFailure(LoginSeleniumTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailure -->
        <test-method status="FAIL" signature="LoginPageTest()[pri:0, instance:com.catalyst.springboot.security.LoginSeleniumTest@39fb3ab6]" name="LoginPageTest" duration-ms="459" started-at="2016-02-02T09:27:29Z" finished-at="2016-02-02T09:27:30Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...lhost:8080/loginPage[]> but was:<...lhost:8080/loginPage[#/home]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...lhost:8080/loginPage[]> but was:<...lhost:8080/loginPage[#/home]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at com.catalyst.springboot.security.LoginSeleniumTest.LoginPageTest(LoginSeleniumTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginPageTest -->
        <test-method status="PASS" signature="LoginSuccess()[pri:0, instance:com.catalyst.springboot.security.LoginSeleniumTest@39fb3ab6]" name="LoginSuccess" duration-ms="2907" started-at="2016-02-02T09:27:30Z" finished-at="2016-02-02T09:27:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccess -->
      </class> <!-- com.catalyst.springboot.security.LoginSeleniumTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
